###配置注册中心项目端口号
server:
  port: 9999
spring:
  ###配置项目应用名
  application:
    name: witmed-registry
  ###配置开启spring boot bean id override 机制
  main:
    allow-bean-definition-overriding: true
###配置Eureka server服务器信息
eureka:
  ###配置server主机名
  instance:
    hostname: localhost
  ###配置client连接信息
  client:
    ###禁止注册中心将自己的服务【器】在其中进行注册
    register-with-eureka: false
    ###禁止本注册中心被其他注册中心发现服务【器】
    fetch-registry: false
    ###暴露注册中心连接地址或者【设置其他client连接注册地址】
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka